# Generated by Django 4.2.6 on 2023-11-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_newmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='materials',
            field=models.CharField(choices=[('cheque', 'Cheque Book'), ('credit', 'Credit Card'), ('debit', 'Debit Card')], default='credit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newmember',
            name='account',
            field=models.CharField(choices=[('current', 'Current Account'), ('savings', 'Savings Account'), ('nri', 'NRI Account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], default=None, max_length=10),
        ),
    ]
