# Generated by Django 4.2.6 on 2023-11-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_newmember_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
