# Generated by Django 4.2.6 on 2023-11-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_newmember_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='materials',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
